In [1]:
import numpy as np  # yup thats it

### Random Sampling
NumPy has some tools for generating random samples. Each has its specific usages and advantages. We will investigate a few of these briefly but again visit the NumPy documentation for a complete referrence. 

In [2]:
# you can create arrays with random values inside
a = np.random.rand(1)  # random number from 0-1 
a         # the 1 in the paranthesis is the dimension of array

array([ 0.88672613])

In [4]:
b = np.random.rand(5,5) # 5x5 array
b

array([[ 0.86177128,  0.67285231,  0.3488154 ,  0.52773414,  0.87891421],
       [ 0.48697326,  0.22476421,  0.42574388,  0.59208076,  0.46938309],
       [ 0.83643901,  0.46699673,  0.12301718,  0.10980369,  0.3247126 ],
       [ 0.41995861,  0.37016867,  0.35911639,  0.05255109,  0.89078558],
       [ 0.64153022,  0.84097852,  0.28141349,  0.73900582,  0.71072679]])

In [5]:
# very similar but this samples from normal distribution
c = np.random.randn(3)
c

array([-0.56792753, -1.08690691,  1.8558237 ])

In [13]:
# random integers 
d = np.random.randint(3)  # 3 is upper bound
d

2

In [19]:
rand = np.random.randint(1,10, size = 5)  # (low, high, size)
rand

array([4, 4, 8, 1, 2])

In [20]:
# using a seed for repeatable results
np.random.seed(0)
rand_arr = np.random.randn(4,3)
rand_arr

array([[ 1.76405235,  0.40015721,  0.97873798],
       [ 2.2408932 ,  1.86755799, -0.97727788],
       [ 0.95008842, -0.15135721, -0.10321885],
       [ 0.4105985 ,  0.14404357,  1.45427351]])

### Common functions for NumPy arrays

In [25]:
# mean of values in an array
print('avg',np.mean(rand))
calc_avg = np.sum(rand)/25
calc_avg

avg 3.8


0.76000000000000001

In [26]:
# variance 
np.var(rand)

5.7599999999999998

In [27]:
# standard deviation
np.std(rand)

2.3999999999999999

In [28]:
# sum of the values
np.sum(rand)

19

In [30]:
# for matrices that are not 1d, specify axis
v = np.array([[1,2],[3,4]])
print(v)
row_sum = np.sum(v, axis=0)
row_sum

[[1 2]
 [3 4]]


array([4, 6])

In [31]:
col_sum = np.sum(v, axis=0)
print(v)
col_sum

[[1 2]
 [3 4]]


array([4, 6])

In [46]:
# you can find the min and max 
sample = np.random.randn(10)
sample_max = np.max(sample)
sample_min = np.min(sample)
print(sample)
print(sample_max)
print(sample_min)

[-0.74475482 -0.82643854 -0.09845252 -0.66347829  1.12663592 -1.07993151
 -1.14746865 -0.43782004 -0.49803245  1.92953205]
1.92953205382
-1.14746865241


In [47]:
# use argmax and argmin to find the index for min and mx values
print(np.argmax(sample))
np.argmin(sample)  # python indexing starts from 0

9


6

In [48]:
# you can combine commands together
data = np.random.randn(4,4) # create random data
print('data',data)
col_totals = np.sum(data, axis=0)  # total the columns
print('totals',col_totals)
max_col_total = (np.argmax(col_totals),np.max(col_totals))
max_col_total  # 1st output is the index, 2nd is the value for max

data [[ 0.94942081  0.08755124 -1.22543552  0.84436298]
 [-1.00021535 -1.5447711   1.18802979  0.31694261]
 [ 0.92085882  0.31872765  0.85683061 -0.65102559]
 [-1.03424284  0.68159452 -0.80340966 -0.68954978]]
totals [-0.16417856 -0.45689768  0.01601522 -0.17926978]


(2, 0.016015221250983869)

In [49]:
# heres how to do in 1 line
max_col_tot = (np.argmax(np.sum(data,axis=0)),
               np.max(np.sum(data,axis=0)))
max_col_tot

(2, 0.016015221250983869)

### PHYSICS EXAMPLE
Lets say everyday we record the average temperature for an object. We are interested in finding the day where the object had its maximum temperature. We will first generate random data and this use numpy functions to find the answer. 

In [50]:
# generate random temperature (must be positive)
temp_data = 50*np.random.rand(100)
print('time of max temp - ',np.argmax(temp_data)+1, 'days')
print('max temp - ',np.max(temp_data), 'degrees Celsius')

time of max temp -  55 days
max temp -  49.0914694909 degrees Celsius


In [51]:
# shape gets the dimensions
a = np.array([[1,2,3],[4,5,6],[7,8,9]])  # syntax for 3x3
print(a)
a.shape

[[1 2 3]
 [4 5 6]
 [7 8 9]]


(3, 3)

In [52]:
# len still works
len(a)

3

In [53]:
# you can index through the elements of the array
print(a[0][0])  # first element of first row
print(a[1][1]) # second element of second row
print(a[-1][-1])  # last element second row
print(a[0])  # first row
print(a[0:2])  # first 2 rows
a[:,0:2]  # first 2 columns

1
5
9
[1 2 3]
[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [4, 5],
       [7, 8]])

In [54]:
# merging numpy arrays horizontally
first = np.array([1,2,3])
second = np.array([4,5,6])
frst_scnd = np.hstack((first,second))
frst_scnd

array([1, 2, 3, 4, 5, 6])

In [55]:
# merge vertically
new_arr = np.vstack((first,second))
new_arr

array([[1, 2, 3],
       [4, 5, 6]])