### EXERCISES

1. Use np.linspace to create an array of angles from 0 to 2$\pi$. 
    * Use the np.sin command on the array. Do the same for np.cos and np.tan. 
    * Convert the array of angles from radians to degrees. 
    
2. Create a 2 by 2 array of random integers. 
    * Transpose the matrix.
    * Find the determinant of the matrix. 
    * Find the inverse of the matrix.
    * Find the eigenvalues and eigenvectors of the matrix.
    
3. Use an array you already have or create a new one and save it as a csv file. Use ls to check the file was saved to the current 
#### PHYSICS PROBLEMS

PROJECTILE MOTION

A ball is launched from ground level at 10 m/s and an angle of 45 degrees. The acceleration due to gravity is -9.8 m/s$^2$ and air resistance can be neglected. 

1. Find the components of the launch velocity:
    * What is the velocity in the upward direction? Define this as  v_y.
    * What is the velocity in the horizontal direction? Define this as v_x. 
    * Determine the time of flight for the ball.
    * Determine the maximum height of the ball.
    * Determine the range of the ball.
    
2. Define a function our a few functions that solves the problem above. 

3. Now, define an array of launch velocities and pass through the function for a given angle. 

4. Do the same but for an array of angles for a given launch velocity.

5. Can you change the function with a for loop to loop through 5 different angles with 10 different launch velocities?

### Exercises
  1) Use the np.sin command on the array. Do the same for np.cos and np.tan. 
  * Convert the array of angles from radians to degrees. 

In [1]:
import numpy as np

In [12]:
a = np.linspace(0,np.pi*2,10)
a

array([ 0.        ,  0.6981317 ,  1.3962634 ,  2.0943951 ,  2.7925268 ,
        3.4906585 ,  4.1887902 ,  4.88692191,  5.58505361,  6.28318531])

In [16]:
print(np.sin(a)) # found sin of a
print(np.cos(a))
print(np.tan(a))
np.degrees(a)  # convereted a to degrees

[  0.00000000e+00   6.42787610e-01   9.84807753e-01   8.66025404e-01
   3.42020143e-01  -3.42020143e-01  -8.66025404e-01  -9.84807753e-01
  -6.42787610e-01  -2.44929360e-16]
[ 1.          0.76604444  0.17364818 -0.5        -0.93969262 -0.93969262
 -0.5         0.17364818  0.76604444  1.        ]
[  0.00000000e+00   8.39099631e-01   5.67128182e+00  -1.73205081e+00
  -3.63970234e-01   3.63970234e-01   1.73205081e+00  -5.67128182e+00
  -8.39099631e-01  -2.44929360e-16]


array([   0.,   40.,   80.,  120.,  160.,  200.,  240.,  280.,  320.,  360.])

### 2. Create a 2 by 2 array of random integers. 
    * Transpose the matrix.
    * Find the determinant of the matrix. 
    * Find the inverse of the matrix.
    * Find the eigenvalues and eigenvectors of the matrix.

In [33]:
randums= np.random.randint(1,101,size=(2,2)) # random 2x2 array 
randums

array([[41, 67],
       [34, 56]])

In [34]:
trans_randums = randums.T  # trasnpose of the matrix
trans_randums

array([[41, 34],
       [67, 56]])

In [35]:
r_det = np.linalg.det(randums) #determinant of the matrix
r_det

17.99999999999995

In [37]:
inv_a = np.linalg.inv(randums) # inverse of the matrix
inv_a

array([[ 3.11111111, -3.72222222],
       [-1.88888889,  2.27777778]])

In [40]:
r_eig= np.linalg.eig(trans_randums)
r_eig

(array([  0.18592338,  96.81407662]), array([[-0.64005407, -0.52023959],
        [ 0.76832987, -0.85402036]]))

### 3. Use an array you already have or create a new one and save it as a csv file. Use ls to check the file was saved to the current 

In [43]:
np.savetxt("randums_array.csv",randums,delimiter=",")
%ls

carlos_1D_projMotion_.ipynb       carlos_ramirez_plottingactivity_.ipynb
Carlos_exercises_1.ipynb          Exercises_3.ipynb
Carlos_Exercises_2.ipynb          NumPy_Ex_2.ipynb
Carlos_ramirez_exercise_3.ipynb   practice lists .ipynb
Carlos_Ramirez_Exercises_4.ipynb  randums_array.csv
Carlos_RAmirez_NumPy_Ex_1.ipynb   toss_rock_up_01.jpg
Carlos_Ramirez_NumPy_Ex_3.ipynb   toss_rock_up_02.jpg


#### PHYSICS PROBLEMS
1. Find the components of the launch velocity:
    * What is the velocity in the upward direction? Define this as  v_y.
    * What is the velocity in the horizontal direction? Define this as v_x. 
    * Determine the time of flight for the ball.
    * Determine the maximum height of the ball.
    * Determine the range of the ball.