### EXERCISES

1. Using one of the methods from np.random create an array of size 4,4 with random numbers from 0-100. You can have these numbers be ints or floats. 
    * Find the standard deviation. Find the variance. Find the mean.  
    * Define an array that has the sum for each column.
    * Define an array that is the product of the elements of the previous array.

2. Practice using indexing for numpy arrays. 
    * Print the first row of the original (4,4) array.
    * Print the last element of the third row.
    * Print the second column. 
    * (Optional) Define an array for each column of the array. Use the np.hstack command to put all the columns back together and get the original matrix.
    
### Finance Applications 
Cash Flow:

$$ CashFlow = Income - Expenses $$

1. Create a function that computes the cash flow when given balues for income and expenses. Make sure to return the cash flow at the end of the function
     
     * Test the function with some values
2. Create a 1d array of 50 random values between 1-20 for income and an array for Expenses

    * Defind an object called Cash Flow that is equal to the results of passing these arrays through your function
    * Use np.argmax/min and np.max/min to determine the maxuimum and minimum Cash Flows from the set from these random values.
    * Next, use np.sum to sum both the income and expenses. Then, again use the function to calculate the total cash flow.

### Exercise 1.
Using one of the methods from np.random create an array of size 4,4 with random numbers from 0-100. You can have these numbers be ints or floats

In [6]:
import numpy as np
a = np.random.rand(4,4)
a

array([[ 0.91167858,  0.61098155,  0.16733474,  0.5796846 ],
       [ 0.73874437,  0.46752908,  0.17495633,  0.67814197],
       [ 0.38239899,  0.52958951,  0.90324335,  0.68920334],
       [ 0.22090867,  0.09717974,  0.59214031,  0.20421372]])

In [13]:
print('avg',np.mean(a))
calc_avg = np.mean(a)
print ('varinace',np.var(a))
print('standard deviation',np.std(a))

avg 0.496745552606
varinace 0.0652079893196
standard deviation 0.255358550512


In [42]:
c = np.array([[1,4,6,7],[3,8,2,9],[9,4,2,7]]) 
col_sum = np.sum(c,axis = 0)
print(col_sum)
c

[13 16 10 23]


array([[1, 4, 6, 7],
       [3, 8, 2, 9],
       [9, 4, 2, 7]])

### Exercise 2.
* Print the first row of the original (4,4) array.
    * Print the last element of the third row.
    * Print the second column. 
    * (Optional) Define an array for each column of the array. Use the np.hstack command to put all the columns back together and get the original matrix.

In [38]:
print('first row =',a[0])
print('last element of third row = ',a[2][3])
a[:,0:2]

first row = [ 0.91167858  0.61098155  0.16733474  0.5796846 ]
last element of third row =  0.689203341123


array([[ 0.91167858,  0.61098155],
       [ 0.73874437,  0.46752908],
       [ 0.38239899,  0.52958951],
       [ 0.22090867,  0.09717974]])

### Finance Applications
1. Create a function that computes the cash flow when given balues for income and expenses. Make sure to return the cash flow at the end of the function
     
     * Test the function with some values